//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Voucher {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Voucher() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("web_payrolls.Resources.Voucher", typeof(Voucher).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Setting.
        /// </summary>
        public static string AccountSetting {
            get {
                return ResourceManager.GetString("AccountSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add More.
        /// </summary>
        public static string AddMore {
            get {
                return ResourceManager.GetString("AddMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Row.
        /// </summary>
        public static string AddRow {
            get {
                return ResourceManager.GetString("AddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Employee.
        /// </summary>
        public static string AllEmployee {
            get {
                return ResourceManager.GetString("AllEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement.
        /// </summary>
        public static string Announcement {
            get {
                return ResourceManager.GetString("Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        public static string ApprovedBy {
            get {
                return ResourceManager.GetString("ApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apv Date.
        /// </summary>
        public static string ApprovedDate {
            get {
                return ResourceManager.GetString("ApprovedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apv Time.
        /// </summary>
        public static string ApprovedTime {
            get {
                return ResourceManager.GetString("ApprovedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booster.
        /// </summary>
        public static string Booster {
            get {
                return ResourceManager.GetString("Booster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check all notification.
        /// </summary>
        public static string Checkallnotification {
            get {
                return ResourceManager.GetString("Checkallnotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        public static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        public static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out Late.
        /// </summary>
        public static string CheckOutLet {
            get {
                return ResourceManager.GetString("CheckOutLet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China.
        /// </summary>
        public static string China {
            get {
                return ResourceManager.GetString("China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm By.
        /// </summary>
        public static string ConfirmBy {
            get {
                return ResourceManager.GetString("ConfirmBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Voucher.
        /// </summary>
        public static string CreateVoucher {
            get {
                return ResourceManager.GetString("CreateVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Entry.
        /// </summary>
        public static string DataEntry {
            get {
                return ResourceManager.GetString("DataEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Confirm.
        /// </summary>
        public static string DateConfirm {
            get {
                return ResourceManager.GetString("DateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Update.
        /// </summary>
        public static string DateUpdate {
            get {
                return ResourceManager.GetString("DateUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAY OFF.
        /// </summary>
        public static string DAYOFF {
            get {
                return ResourceManager.GetString("DAYOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease.
        /// </summary>
        public static string Decrease {
            get {
                return ResourceManager.GetString("Decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Information.
        /// </summary>
        public static string EmployeeInformation {
            get {
                return ResourceManager.GetString("EmployeeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Rent.
        /// </summary>
        public static string EndRent {
            get {
                return ResourceManager.GetString("EndRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries.
        /// </summary>
        public static string Entries {
            get {
                return ResourceManager.GetString("Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.
        /// </summary>
        public static string Excel {
            get {
                return ResourceManager.GetString("Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        public static string Exchange {
            get {
                return ResourceManager.GetString("Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign.
        /// </summary>
        public static string Foreign {
            get {
                return ResourceManager.GetString("Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget​ Scan.
        /// </summary>
        public static string Forget {
            get {
                return ResourceManager.GetString("Forget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOD.
        /// </summary>
        public static string HOD {
            get {
                return ResourceManager.GetString("HOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        public static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        public static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Card.
        /// </summary>
        public static string idcard {
            get {
                return ResourceManager.GetString("idcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Money.
        /// </summary>
        public static string InputMoney {
            get {
                return ResourceManager.GetString("InputMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khmer.
        /// </summary>
        public static string Khmer {
            get {
                return ResourceManager.GetString("Khmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        public static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type.
        /// </summary>
        public static string LeaveType {
            get {
                return ResourceManager.GetString("LeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List All Staff.
        /// </summary>
        public static string ListAllStaff {
            get {
                return ResourceManager.GetString("ListAllStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Employee.
        /// </summary>
        public static string ListEmployee {
            get {
                return ResourceManager.GetString("ListEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Roster.
        /// </summary>
        public static string ListRoster {
            get {
                return ResourceManager.GetString("ListRoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Voucher.
        /// </summary>
        public static string ListVoucher {
            get {
                return ResourceManager.GetString("ListVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Voucher Item.
        /// </summary>
        public static string ListVoucherItem {
            get {
                return ResourceManager.GetString("ListVoucherItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money.
        /// </summary>
        public static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month Of Year.
        /// </summary>
        public static string MonthOfYear {
            get {
                return ResourceManager.GetString("MonthOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Balance.
        /// </summary>
        public static string MyBalance {
            get {
                return ResourceManager.GetString("MyBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Document.
        /// </summary>
        public static string MyDocument {
            get {
                return ResourceManager.GetString("MyDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Leave Manage.
        /// </summary>
        public static string MyLeaveManage {
            get {
                return ResourceManager.GetString("MyLeaveManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Pay Sleep.
        /// </summary>
        public static string MyPaySleep {
            get {
                return ResourceManager.GetString("MyPaySleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Employee.
        /// </summary>
        public static string NewEmployee {
            get {
                return ResourceManager.GetString("NewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new messages.
        /// </summary>
        public static string newmessages {
            get {
                return ResourceManager.GetString("newmessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to សេចក្តីជូនដំណឹង.
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OT.
        /// </summary>
        public static string ot {
            get {
                return ResourceManager.GetString("ot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OT Date.
        /// </summary>
        public static string OTDate {
            get {
                return ResourceManager.GetString("OTDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OT Price.
        /// </summary>
        public static string OTPrice {
            get {
                return ResourceManager.GetString("OTPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO.
        /// </summary>
        public static string OTTo {
            get {
                return ResourceManager.GetString("OTTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime.
        /// </summary>
        public static string Overtime {
            get {
                return ResourceManager.GetString("Overtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime Hour.
        /// </summary>
        public static string OverTimeHour {
            get {
                return ResourceManager.GetString("OverTimeHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Of Month.
        /// </summary>
        public static string PriceOfMonth {
            get {
                return ResourceManager.GetString("PriceOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Color.
        /// </summary>
        public static string ProductColor {
            get {
                return ResourceManager.GetString("ProductColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Measure.
        /// </summary>
        public static string ProductMeasure {
            get {
                return ResourceManager.GetString("ProductMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Size.
        /// </summary>
        public static string ProductSize {
            get {
                return ResourceManager.GetString("ProductSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty In Month.
        /// </summary>
        public static string QtyInMonth {
            get {
                return ResourceManager.GetString("QtyInMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string Rent {
            get {
                return ResourceManager.GetString("Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster.
        /// </summary>
        public static string Roster {
            get {
                return ResourceManager.GetString("Roster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Type.
        /// </summary>
        public static string SalaryType {
            get {
                return ResourceManager.GetString("SalaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save New.
        /// </summary>
        public static string SaveNew {
            get {
                return ResourceManager.GetString("SaveNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search here.
        /// </summary>
        public static string Searchhere {
            get {
                return ResourceManager.GetString("Searchhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all E-Mails.
        /// </summary>
        public static string SeeallEMails {
            get {
                return ResourceManager.GetString("SeeallEMails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        public static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Rent.
        /// </summary>
        public static string StartRent {
            get {
                return ResourceManager.GetString("StartRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suptotal.
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string SystemManager {
            get {
                return ResourceManager.GetString("SystemManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Confirm.
        /// </summary>
        public static string TimeConfirm {
            get {
                return ResourceManager.GetString("TimeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Sheet.
        /// </summary>
        public static string TimeSheet {
            get {
                return ResourceManager.GetString("TimeSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Update.
        /// </summary>
        public static string TimeUpdate {
            get {
                return ResourceManager.GetString("TimeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Cost.
        /// </summary>
        public static string UnitCost {
            get {
                return ResourceManager.GetString("UnitCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update by.
        /// </summary>
        public static string UpdateBy {
            get {
                return ResourceManager.GetString("UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Profile.
        /// </summary>
        public static string ViewProfile {
            get {
                return ResourceManager.GetString("ViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher.
        /// </summary>
        public static string Voucher_ {
            get {
                return ResourceManager.GetString("Voucher_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Date.
        /// </summary>
        public static string VoucherDate {
            get {
                return ResourceManager.GetString("VoucherDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher No.
        /// </summary>
        public static string VoucherNo {
            get {
                return ResourceManager.GetString("VoucherNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Rent.
        /// </summary>
        public static string VoucherRent {
            get {
                return ResourceManager.GetString("VoucherRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher.
        /// </summary>
        public static string Vouchers {
            get {
                return ResourceManager.GetString("Vouchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string VoucherStaff {
            get {
                return ResourceManager.GetString("VoucherStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wage deducts.
        /// </summary>
        public static string Wagededucts {
            get {
                return ResourceManager.GetString("Wagededucts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have.
        /// </summary>
        public static string Youhave {
            get {
                return ResourceManager.GetString("Youhave", resourceCulture);
            }
        }
    }
}
