//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.View {
    
    
    public partial class Test {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new web_payrolls.View.Layout Master {
            get {
                return ((web_payrolls.View.Layout)(base.Master));
            }
        }
    }
}
