//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAnnouncment
    {
        public int PK_Announment_Id { get; set; }
        public Nullable<int> FK_Loc_Id { get; set; }
        public string Title { get; set; }
        public string Picture { get; set; }
        public string Descr { get; set; }
        public string Title_Booter { get; set; }
        public string Title1 { get; set; }
        public string Picture1 { get; set; }
        public string Descr1 { get; set; }
        public string Title_Booter1 { get; set; }
        public string Title2 { get; set; }
        public string Picture2 { get; set; }
        public string Descr2 { get; set; }
        public string Title_Booter2 { get; set; }
        public Nullable<int> User_Update { get; set; }
        public string Date_Update { get; set; }
        public string Time_Update { get; set; }
    
        public virtual tblLocation tblLocation { get; set; }
    }
}
