//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBrokendBalance
    {
        public int PK_Brokend_Bal_Id { get; set; }
        public Nullable<int> FK_Return_Inventory_Id { get; set; }
        public Nullable<int> FK_Dep_Id { get; set; }
        public Nullable<int> Brokend_QTY { get; set; }
    
        public virtual tblReturnInventory tblReturnInventory { get; set; }
    }
}
