//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCut_Money
    {
        public int PK_Cut_Id { get; set; }
        public Nullable<int> FK_Com_Id { get; set; }
        public string Lev_Name { get; set; }
        public string Descr { get; set; }
        public Nullable<double> Cut_Percent { get; set; }
        public Nullable<int> User_Update { get; set; }
        public string Date_Update { get; set; }
        public string Time_Update { get; set; }
    }
}
