//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblInventory()
        {
            this.tblLost_Inventory = new HashSet<tblLost_Inventory>();
            this.tblLostBalances = new HashSet<tblLostBalance>();
            this.tblStock_In_Inventory_Id = new HashSet<tblStock_In_Inventory_Id>();
            this.tblStockBalance_Inventory = new HashSet<tblStockBalance_Inventory>();
            this.tblStockBalanceInventoryInDepartments = new HashSet<tblStockBalanceInventoryInDepartment>();
            this.tblStockinventoryOnDepartments = new HashSet<tblStockinventoryOnDepartment>();
        }
    
        public int PK_Inventory_Id { get; set; }
        public Nullable<int> FK_Model_Of_Inventory_Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<double> Unit_Price { get; set; }
        public string Picture { get; set; }
        public string Descr { get; set; }
        public Nullable<int> User_Update { get; set; }
        public string Date_Update { get; set; }
        public string Time_Update { get; set; }
    
        public virtual tblModel_Of_Inventory tblModel_Of_Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLost_Inventory> tblLost_Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLostBalance> tblLostBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStock_In_Inventory_Id> tblStock_In_Inventory_Id { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStockBalance_Inventory> tblStockBalance_Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStockBalanceInventoryInDepartment> tblStockBalanceInventoryInDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStockinventoryOnDepartment> tblStockinventoryOnDepartments { get; set; }
    }
}
