//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLocation()
        {
            this.tblAnnouncments = new HashSet<tblAnnouncment>();
            this.tblDepartments = new HashSet<tblDepartment>();
            this.tblProduction_StockIn_Cut_On_Loc = new HashSet<tblProduction_StockIn_Cut_On_Loc>();
            this.tblSupplyers = new HashSet<tblSupplyer>();
            this.tblVoucher_Rent_Invertory_Rent_And_Other_Voucher = new HashSet<tblVoucher_Rent_Invertory_Rent_And_Other_Voucher>();
        }
    
        public int PK_Location_Id { get; set; }
        public Nullable<int> FK_Comp_Id { get; set; }
        public string Loc_Name { get; set; }
        public string Descr { get; set; }
        public Nullable<int> User_Update { get; set; }
        public string Date_Update { get; set; }
        public string Time_Update { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAnnouncment> tblAnnouncments { get; set; }
        public virtual tblCompany tblCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDepartment> tblDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduction_StockIn_Cut_On_Loc> tblProduction_StockIn_Cut_On_Loc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSupplyer> tblSupplyers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVoucher_Rent_Invertory_Rent_And_Other_Voucher> tblVoucher_Rent_Invertory_Rent_And_Other_Voucher { get; set; }
    }
}
