//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduction_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduction_Product()
        {
            this.tblProduction_Color = new HashSet<tblProduction_Color>();
            this.tblProduction_Grade = new HashSet<tblProduction_Grade>();
        }
    
        public long PK_Pro_Id { get; set; }
        public Nullable<long> FK_ProType_Id { get; set; }
        public string Pro_Name { get; set; }
        public string Picture_Path { get; set; }
        public Nullable<int> User_Update { get; set; }
        public string Date_Update { get; set; }
        public string Time_Update { get; set; }
        public string Descr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduction_Color> tblProduction_Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduction_Grade> tblProduction_Grade { get; set; }
        public virtual tblProduction_ProductType tblProduction_ProductType { get; set; }
    }
}
