//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduction_Color
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduction_Color()
        {
            this.tblProduction_Size = new HashSet<tblProduction_Size>();
        }
    
        public long PK_Color_Id { get; set; }
        public Nullable<long> FK_Pro_Id { get; set; }
        public string BarCode { get; set; }
        public string QR_Code { get; set; }
        public string Color_Name { get; set; }
        public Nullable<int> User_Update { get; set; }
        public string Date_Update { get; set; }
        public string Time_Update { get; set; }
        public string Descr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduction_Size> tblProduction_Size { get; set; }
        public virtual tblProduction_Product tblProduction_Product { get; set; }
    }
}
