//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduction_Size
    {
        public long PK_Size_Id { get; set; }
        public Nullable<long> FK_Color_Id { get; set; }
        public string Size_Name { get; set; }
        public Nullable<int> User_Update { get; set; }
        public string Date_Update { get; set; }
        public string Time_Update { get; set; }
        public string Descr { get; set; }
    
        public virtual tblProduction_Color tblProduction_Color { get; set; }
    }
}
