//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduction_StockIn_Product_Cut_Balance
    {
        public long PK_StockIn_Product_Cut_Balance_Id { get; set; }
        public Nullable<long> FK_Grade_Id { get; set; }
        public Nullable<long> FK_Com_Id { get; set; }
        public string Stock_In_Product_Cut_No_Id { get; set; }
        public string Stock_In_Type { get; set; }
        public Nullable<int> QTY_Balance { get; set; }
    }
}
