//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPermission
    {
        public long PK_Permission_Id { get; set; }
        public Nullable<long> FK_Staff_Id { get; set; }
        public Nullable<bool> View_Profile { get; set; }
        public Nullable<byte> View_Measure { get; set; }
    
        public virtual tblStaff tblStaff { get; set; }
    }
}
