//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduction_StockIn_Cut_On_Loc
    {
        public long PK_StockIn_Cut_On_Loc_Id { get; set; }
        public Nullable<long> FK_Grade_Id { get; set; }
        public Nullable<int> FK_Loc_Id { get; set; }
        public Nullable<int> In_QTY { get; set; }
        public string FK_Comp_From_Id { get; set; }
        public string Code_Product { get; set; }
        public Nullable<long> StockIn_Cut_On_LocNo_Id { get; set; }
        public string Stock_In_Type { get; set; }
        public Nullable<int> U_Update { get; set; }
        public string In_Date { get; set; }
        public string In_Time { get; set; }
        public Nullable<int> Confirm_PK_U_Id { get; set; }
        public string Confirm_Date { get; set; }
        public string Confirm_Time { get; set; }
        public string Confirm_Status { get; set; }
        public string Descr { get; set; }
    
        public virtual tblLocation tblLocation { get; set; }
        public virtual tblProduction_Grade tblProduction_Grade { get; set; }
        public virtual tblProduction_StockIn_Cut_On_LocNo tblProduction_StockIn_Cut_On_LocNo { get; set; }
    }
}
