//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduction_Tranfer_From_LocTo_Comp
    {
        public long PK_Tranfer_From_LocTo_Comp_Id { get; set; }
        public Nullable<long> FK_Grade_Id { get; set; }
        public Nullable<int> FK_Com_Id { get; set; }
        public Nullable<int> FK_Loc_From_Id { get; set; }
        public string Code_Product { get; set; }
        public Nullable<int> In_QTY { get; set; }
        public string Tranfer_In_Type { get; set; }
        public Nullable<int> U_Update { get; set; }
        public string Tranfer_Date { get; set; }
        public string Tranfer_Time { get; set; }
        public string Tranfer_Status { get; set; }
        public Nullable<int> Confirm_PK_U_Id { get; set; }
        public string Confirm_Date { get; set; }
        public string Confirm_Time { get; set; }
        public string Desce { get; set; }
    }
}
