//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduction_StockIn_Cut_On_LocNo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduction_StockIn_Cut_On_LocNo()
        {
            this.tblProduction_StockIn_Cut_On_Loc = new HashSet<tblProduction_StockIn_Cut_On_Loc>();
        }
    
        public long PK_StockIn_Cut_On_LocNo_Id { get; set; }
        public Nullable<long> StockIn_Cut_On_LocNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduction_StockIn_Cut_On_Loc> tblProduction_StockIn_Cut_On_Loc { get; set; }
    }
}
