//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduction_Grade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduction_Grade()
        {
            this.tblProduction_StockIn_Cut_On_LocBalance = new HashSet<tblProduction_StockIn_Cut_On_LocBalance>();
            this.tblProduction_StockIn_Complete_Balance = new HashSet<tblProduction_StockIn_Complete_Balance>();
            this.tblProducttion_StockIn_Complete_Product = new HashSet<tblProducttion_StockIn_Complete_Product>();
            this.tblProduction_StockIn_Cut_On_Loc = new HashSet<tblProduction_StockIn_Cut_On_Loc>();
            this.tblProduction_Stock_In_Product_Import = new HashSet<tblProduction_Stock_In_Product_Import>();
            this.tblProduction_PK_Stock_In_Product_Import_Balance = new HashSet<tblProduction_PK_Stock_In_Product_Import_Balance>();
            this.tblProduction_PK_Stock_In_Product_Cut = new HashSet<tblProduction_PK_Stock_In_Product_Cut>();
            this.tblProduction_Use_Fabrik_On_Cut = new HashSet<tblProduction_Use_Fabrik_On_Cut>();
            this.tblProduction_Use_Fabrik_On_Cut_Balance = new HashSet<tblProduction_Use_Fabrik_On_Cut_Balance>();
        }
    
        public long PK_Grade_Id { get; set; }
        public Nullable<long> FK_Product_Id { get; set; }
        public string QR_Code { get; set; }
        public string BarCode { get; set; }
        public string Measu_Name { get; set; }
        public string Grade_Name { get; set; }
        public Nullable<double> Double_Whole_Price { get; set; }
        public Nullable<double> Whole_Price { get; set; }
        public Nullable<double> Unit_Price { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> Normal_Price { get; set; }
        public string Picture_Path { get; set; }
        public Nullable<double> Discount { get; set; }
        public string Start_Dis { get; set; }
        public string End_Dis { get; set; }
        public string Status_Dis { get; set; }
        public string Pro_Status { get; set; }
        public Nullable<int> User_Update { get; set; }
        public string Date_Update { get; set; }
        public string Time_Update { get; set; }
        public string Descr { get; set; }
        public string Picture_Detail { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string Code_Product { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduction_StockIn_Cut_On_LocBalance> tblProduction_StockIn_Cut_On_LocBalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduction_StockIn_Complete_Balance> tblProduction_StockIn_Complete_Balance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProducttion_StockIn_Complete_Product> tblProducttion_StockIn_Complete_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduction_StockIn_Cut_On_Loc> tblProduction_StockIn_Cut_On_Loc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduction_Stock_In_Product_Import> tblProduction_Stock_In_Product_Import { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduction_PK_Stock_In_Product_Import_Balance> tblProduction_PK_Stock_In_Product_Import_Balance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduction_PK_Stock_In_Product_Cut> tblProduction_PK_Stock_In_Product_Cut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduction_Use_Fabrik_On_Cut> tblProduction_Use_Fabrik_On_Cut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduction_Use_Fabrik_On_Cut_Balance> tblProduction_Use_Fabrik_On_Cut_Balance { get; set; }
        public virtual tblProduction_Product tblProduction_Product { get; set; }
    }
}
