//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPuchase
    {
        public long PK_Puchase_Id { get; set; }
        public Nullable<long> FK_Staff_Id { get; set; }
        public Nullable<long> FK_PuchaseNo_Id { get; set; }
        public string Date_Puchase { get; set; }
        public string Time_Puchase { get; set; }
        public string Name_Product { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Total_Price { get; set; }
        public string Picture_Product { get; set; }
        public string Status { get; set; }
        public Nullable<int> User_Confirm { get; set; }
        public string Date_Confirm { get; set; }
        public string Time_Confirm { get; set; }
    
        public virtual tblPuchaseNo tblPuchaseNo { get; set; }
        public virtual tblStaff tblStaff { get; set; }
    }
}
