//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReturnInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblReturnInventory()
        {
            this.tblBrokendBalances = new HashSet<tblBrokendBalance>();
        }
    
        public int PK_Return_Inventory_Id { get; set; }
        public Nullable<int> FK_Return_InventoryNo_Id { get; set; }
        public Nullable<int> Return_Brokend_User_Update { get; set; }
        public string Return_Brokent_Date_Update { get; set; }
        public string Return_Brokent_Time_Update { get; set; }
        public string Return_Type { get; set; }
        public Nullable<int> Return_QTY { get; set; }
        public Nullable<double> Unit_Price { get; set; }
        public Nullable<double> Total_Price { get; set; }
        public Nullable<int> User_Confrim { get; set; }
        public string Date_Confirm { get; set; }
        public string Time_Confirm { get; set; }
        public string Return_Status { get; set; }
        public string Descr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBrokendBalance> tblBrokendBalances { get; set; }
        public virtual tblReturnInventoryNo tblReturnInventoryNo { get; set; }
    }
}
