//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRemain_Leave
    {
        public long PK_Remain_Leave_Id { get; set; }
        public Nullable<long> FK_Staff_Id { get; set; }
        public Nullable<double> OFF_Remain { get; set; }
        public Nullable<double> AL_Remain { get; set; }
        public Nullable<double> PH_Remain { get; set; }
        public Nullable<double> SIC_Remain { get; set; }
        public Nullable<double> UPL_Remain { get; set; }
        public Nullable<double> AB_Remain { get; set; }
        public Nullable<double> CM_Remain { get; set; }
        public Nullable<int> User_Updae { get; set; }
        public string Date_Update { get; set; }
        public string Time_Update { get; set; }
    }
}
