//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStaff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStaff()
        {
            this.tblForget_Scan = new HashSet<tblForget_Scan>();
            this.tblInputLastyears = new HashSet<tblInputLastyear>();
            this.tblNotifications = new HashSet<tblNotification>();
            this.tblOver_Time = new HashSet<tblOver_Time>();
            this.tblPermissions = new HashSet<tblPermission>();
            this.tblPuchases = new HashSet<tblPuchase>();
            this.tblRosters = new HashSet<tblRoster>();
            this.tblSalary_Type = new HashSet<tblSalary_Type>();
            this.tblShareHolders = new HashSet<tblShareHolder>();
            this.tblSum_Sal = new HashSet<tblSum_Sal>();
        }
    
        public long PK_Staff_Id { get; set; }
        public Nullable<int> FK_Pos_Id { get; set; }
        public string Staff_Name { get; set; }
        public string Sex { get; set; }
        public string Staff_DOB { get; set; }
        public string Marry_Status { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> Wife { get; set; }
        public Nullable<int> Son { get; set; }
        public Nullable<int> Daughter { get; set; }
        public string Tell { get; set; }
        public string Account_Name { get; set; }
        public string Account_Number { get; set; }
        public string Address { get; set; }
        public string Identity_Card { get; set; }
        public string Identify_Picture { get; set; }
        public string Staff_Id_Card { get; set; }
        public string Serail_Card { get; set; }
        public string Staff_Status { get; set; }
        public string Join_date { get; set; }
        public string End_Date { get; set; }
        public string Photo { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string No_Scan { get; set; }
        public Nullable<int> User_Update { get; set; }
        public string Date_Update { get; set; }
        public string Time_Update { get; set; }
        public byte[] FingerPrintTemplate { get; set; }
        public string LoginCodeGeneration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblForget_Scan> tblForget_Scan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInputLastyear> tblInputLastyears { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNotification> tblNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOver_Time> tblOver_Time { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPermission> tblPermissions { get; set; }
        public virtual tblPosition tblPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPuchase> tblPuchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRoster> tblRosters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalary_Type> tblSalary_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblShareHolder> tblShareHolders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSum_Sal> tblSum_Sal { get; set; }
    }
}
