//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShareHolder
    {
        public long PK_ShareHolder_Id { get; set; }
        public Nullable<long> FK_Staff_Id { get; set; }
        public Nullable<int> FK_Com_Id { get; set; }
        public string Date_Input { get; set; }
        public string Time_Input { get; set; }
        public Nullable<double> Increase_Money { get; set; }
        public string Note { get; set; }
        public Nullable<int> User_Update { get; set; }
        public string Date_Update { get; set; }
        public string Time_Update { get; set; }
    
        public virtual tblStaff tblStaff { get; set; }
    }
}
