//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStockinventoryOnDepartment
    {
        public int Pk_StockIN_Inventory_On_Department_Id { get; set; }
        public Nullable<int> FK_Inventory_ID { get; set; }
        public Nullable<int> FK_Department_ID { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<double> Unit_Price { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Type_Inventory { get; set; }
        public Nullable<int> StockIn_By { get; set; }
        public string Date_StockIn { get; set; }
        public string Time_StockIn { get; set; }
        public string Status { get; set; }
        public Nullable<int> User_Confirm { get; set; }
        public string Date_Confirm { get; set; }
        public string Time_Confirm { get; set; }
        public string Descr { get; set; }
    
        public virtual tblDepartment tblDepartment { get; set; }
        public virtual tblInventory tblInventory { get; set; }
    }
}
