//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSum_Sal
    {
        public long PK_Sum_sal_Id { get; set; }
        public Nullable<long> FK_Staff_Id { get; set; }
        public Nullable<int> Num_Year { get; set; }
        public Nullable<int> Num_Month { get; set; }
        public string DAY1 { get; set; }
        public string DAY2 { get; set; }
        public string DAY3 { get; set; }
        public string DAY4 { get; set; }
        public string DAY5 { get; set; }
        public string DAY6 { get; set; }
        public string DAY7 { get; set; }
        public string DAY8 { get; set; }
        public string DAY9 { get; set; }
        public string DAY10 { get; set; }
        public string DAY11 { get; set; }
        public string DAY12 { get; set; }
        public string DAY13 { get; set; }
        public string DAY14 { get; set; }
        public string DAY15 { get; set; }
        public string DAY16 { get; set; }
        public string DAY17 { get; set; }
        public string DAY18 { get; set; }
        public string DAY19 { get; set; }
        public string DAY20 { get; set; }
        public string DAY21 { get; set; }
        public string DAY22 { get; set; }
        public string DAY23 { get; set; }
        public string DAY24 { get; set; }
        public string DAY25 { get; set; }
        public string DAY26 { get; set; }
        public string DAY27 { get; set; }
        public string DAY28 { get; set; }
        public string DAY29 { get; set; }
        public string DAY30 { get; set; }
        public string DAY31 { get; set; }
        public string Sal_Type { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<double> Accommodation { get; set; }
        public Nullable<double> Food { get; set; }
        public Nullable<double> insurance { get; set; }
        public Nullable<double> Gym { get; set; }
        public Nullable<double> Money_Prim { get; set; }
        public Nullable<double> Money_LastYear { get; set; }
        public Nullable<double> Gasoline { get; set; }
        public string Money_Lo { get; set; }
        public Nullable<double> NetCash { get; set; }
        public Nullable<double> Card_Phone { get; set; }
        public Nullable<double> Travel { get; set; }
        public string Tax { get; set; }
        public Nullable<double> Sal_Total { get; set; }
        public Nullable<double> Leave_Total { get; set; }
        public Nullable<double> OT_Total { get; set; }
        public Nullable<double> Forget_Scan_Total { get; set; }
        public Nullable<double> Check_In_Late { get; set; }
        public string Bonus { get; set; }
        public string Company_Mission { get; set; }
        public string Input_Money { get; set; }
        public string Grand_Total { get; set; }
    
        public virtual tblStaff tblStaff { get; set; }
    }
}
