//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStock_In_Inventory_Id
    {
        public long PK_Stock_In_Inventory_Id { get; set; }
        public Nullable<int> FK_Inventory_Id { get; set; }
        public Nullable<int> FK_Supp_Id { get; set; }
        public Nullable<int> FK_Com_Id { get; set; }
        public byte[] Stock_In { get; set; }
        public Nullable<double> Unit_Price { get; set; }
        public Nullable<double> Amount { get; set; }
        public byte[] User_Update { get; set; }
        public string Date_Update { get; set; }
        public string Time_Update { get; set; }
        public string Descr { get; set; }
        public string In_Status { get; set; }
        public Nullable<int> User_Confirm { get; set; }
        public string Date_Confirm { get; set; }
        public string Time_Confirm { get; set; }
    
        public virtual tblInventory tblInventory { get; set; }
    }
}
