//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalary_Type
    {
        public long PK_Sal_Type_Id { get; set; }
        public Nullable<long> FK_Sta_Id { get; set; }
        public string Sal_Type { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<double> Card_Phone { get; set; }
        public Nullable<double> Gym { get; set; }
        public Nullable<double> Accommodation { get; set; }
        public Nullable<double> Food { get; set; }
        public Nullable<double> insurance { get; set; }
        public Nullable<double> Money_Prim { get; set; }
        public Nullable<double> Travel { get; set; }
        public Nullable<double> Gasoline { get; set; }
        public Nullable<double> OT_Unit_Price { get; set; }
        public Nullable<double> Work_Hour_Taget { get; set; }
        public Nullable<double> Relax_Hour { get; set; }
        public Nullable<double> Off_Day { get; set; }
        public Nullable<double> AL_Day { get; set; }
        public Nullable<double> PH_Day { get; set; }
        public Nullable<double> Sick { get; set; }
        public Nullable<double> UPL { get; set; }
        public Nullable<double> AB { get; set; }
        public Nullable<double> CM { get; set; }
        public Nullable<int> User_Update { get; set; }
        public string Date_Update { get; set; }
        public string Time_Update { get; set; }
    
        public virtual tblStaff tblStaff { get; set; }
    }
}
