//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStockBalance_Inventory
    {
        public int PK_StockBl_Id { get; set; }
        public Nullable<int> FK_Inventory_Id { get; set; }
        public Nullable<int> FK_Com_Id { get; set; }
        public Nullable<int> Stock_Bal_Qty { get; set; }
    
        public virtual tblInventory tblInventory { get; set; }
    }
}
