//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStockBalanceInventoryInDepartment
    {
        public int PK_StockBal_InDepartment_ID { get; set; }
        public Nullable<int> FK_Inventory_Id { get; set; }
        public Nullable<int> FK_Depart_Id { get; set; }
        public Nullable<int> QTY_Balance { get; set; }
    
        public virtual tblDepartment tblDepartment { get; set; }
        public virtual tblInventory tblInventory { get; set; }
    }
}
