//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrack_User
    {
        public long PK_Track_User_Id { get; set; }
        public Nullable<long> User_Id { get; set; }
        public string Online { get; set; }
        public string IP { get; set; }
        public string City { get; set; }
        public string POS_Code { get; set; }
        public string Map { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
    }
}
