//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser_Tracking
    {
        public long PK_U_Tracking_Id { get; set; }
        public Nullable<long> U_Id { get; set; }
        public string Online { get; set; }
        public string IP { get; set; }
        public string City { get; set; }
        public string Region_Code { get; set; }
        public string Country_Name { get; set; }
        public string Country_Code { get; set; }
        public string Continent_Name { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string ISP { get; set; }
        public string Organization { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
    }
}
