//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVoucher_No
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVoucher_No()
        {
            this.tblVouchers = new HashSet<tblVoucher>();
        }
    
        public int PK_Voucher_No_Id { get; set; }
        public Nullable<int> VoucherNo { get; set; }
        public Nullable<int> Aprove_PK_U_Id { get; set; }
        public string Aprove_Date { get; set; }
        public string Aprove_Time { get; set; }
        public string Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVoucher> tblVouchers { get; set; }
    }
}
