//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_payrolls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVoucher_Rent_Invertory_Rent_And_Other_Voucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVoucher_Rent_Invertory_Rent_And_Other_Voucher()
        {
            this.tblVouchers = new HashSet<tblVoucher>();
        }
    
        public int PK_Voucher_Rent_Other_Id { get; set; }
        public Nullable<int> FK_loc_id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> QTY_in_Month { get; set; }
        public Nullable<double> Unit_Price_in_Month { get; set; }
        public Nullable<double> Amount_In_Month { get; set; }
        public string Status { get; set; }
        public string Picture { get; set; }
        public string Start_Rent { get; set; }
        public string End_Rent { get; set; }
        public string Amount_Month_Year_Rent { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<int> User_Update { get; set; }
        public string Date_Update { get; set; }
        public string Time_Update { get; set; }
    
        public virtual tblLocation tblLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVoucher> tblVouchers { get; set; }
    }
}
